package com.pahimar.ee3.client.renderer.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import org.lwjgl.opengl.GL11;

public class ModelTransmutationTablet extends ModelBase
{
    public ModelRenderer wick_LF;
    public ModelRenderer CirclePad;
    public ModelRenderer Candle_LB;
    public ModelRenderer wick_RB;
    public ModelRenderer wick_RF;
    public ModelRenderer wick_LB;
    public ModelRenderer pedRB3;
    public ModelRenderer pedRB1;
    public ModelRenderer pedRB4;
    public ModelRenderer pedRB2;
    public ModelRenderer pedLB1;
    public ModelRenderer pedLB2;
    public ModelRenderer pedLB3;
    public ModelRenderer pedLB4;
    public ModelRenderer pedRF1;
    public ModelRenderer pedRF2;
    public ModelRenderer pedRF3;
    public ModelRenderer pedRF4;
    public ModelRenderer pedLF1;
    public ModelRenderer pedLF2;
    public ModelRenderer pedLF3;
    public ModelRenderer pedLF4;
    public ModelRenderer Base;
    public ModelRenderer Candle_LB_1;
    public ModelRenderer Candle_LB_2;
    public ModelRenderer Candle_LB_3;
    public ModelRenderer Candle_LB_4;
    public ModelRenderer Candle_LF;
    public ModelRenderer Candle_drib2;
    public ModelRenderer Candle_drib3;
    public ModelRenderer Candle_drib1;
    public ModelRenderer Candle_drib4;
    public ModelRenderer Candle_RF;
    public ModelRenderer Candle_drib5;
    public ModelRenderer Candle_drib6;
    public ModelRenderer Candle_drib7;
    public ModelRenderer Candle_drib8;
    public ModelRenderer Candle_drib9;
    public ModelRenderer Candle_drib10;

    public ModelTransmutationTablet()
    {
        this.textureWidth = 256;
        this.textureHeight = 128;
        this.wick_RF = new ModelRenderer(this, 64, 69);
        this.wick_RF.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wick_RF.addBox(30.3F, -2.0F, -31.3F, 1, 2, 1, 0.0F);
        this.Candle_drib9 = new ModelRenderer(this, 48, 59);
        this.Candle_drib9.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib9.addBox(20.0F, 2.0F, -19.0F, 1, 4, 1, 0.0F);
        this.Candle_LB_4 = new ModelRenderer(this, 48, 59);
        this.Candle_LB_4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_LB_4.addBox(-19.0F, 4.0F, 20.0F, 1, 2, 1, 0.0F);
        this.Candle_drib5 = new ModelRenderer(this, 48, 59);
        this.Candle_drib5.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib5.addBox(16.0F, 3.0F, -19.0F, 1, 3, 1, 0.0F);
        this.pedLB4 = new ModelRenderer(this, 64, 58);
        this.pedLB4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLB4.addBox(16.0F, 14.0F, 16.0F, 5, 2, 5, 0.0F);
        this.CirclePad = new ModelRenderer(this, 80, 38);
        this.CirclePad.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.CirclePad.addBox(-16.0F, 14.0F, -16.0F, 32, 2, 32, 0.0F);
        this.Candle_LB_2 = new ModelRenderer(this, 48, 59);
        this.Candle_LB_2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_LB_2.addBox(-21.0F, 3.0F, 18.0F, 1, 3, 1, 0.0F);
        this.pedLB2 = new ModelRenderer(this, 64, 58);
        this.pedLB2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLB2.addBox(16.0F, 8.0F, 16.0F, 5, 2, 5, 0.0F);
        this.Candle_drib8 = new ModelRenderer(this, 48, 59);
        this.Candle_drib8.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib8.addBox(18.0F, 5.0F, 20.0F, 1, 1, 1, 0.0F);
        this.pedLF3 = new ModelRenderer(this, 84, 58);
        this.pedLF3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLF3.addBox(-20.0F, 10.0F, 17.0F, 3, 4, 3, 0.0F);
        this.Candle_RF = new ModelRenderer(this, 48, 59);
        this.Candle_RF.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_RF.addBox(17.0F, 0.0F, -20.0F, 3, 6, 3, 0.0F);
        this.Candle_drib4 = new ModelRenderer(this, 48, 59);
        this.Candle_drib4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib4.addBox(18.0F, 4.0F, -21.0F, 1, 2, 1, 0.0F);
        this.wick_RB = new ModelRenderer(this, 64, 69);
        this.wick_RB.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wick_RB.addBox(30.3F, -2.0F, 30.3F, 1, 2, 1, 0.0F);
        this.Candle_LB = new ModelRenderer(this, 48, 59);
        this.Candle_LB.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_LB.addBox(-19.0F, 5.0F, 16.0F, 1, 1, 1, 0.0F);
        this.pedRF2 = new ModelRenderer(this, 64, 58);
        this.pedRF2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRF2.addBox(-21.0F, 8.0F, -21.0F, 5, 2, 5, 0.0F);
        this.pedLF2 = new ModelRenderer(this, 64, 58);
        this.pedLF2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLF2.addBox(-21.0F, 8.0F, 16.0F, 5, 2, 5, 0.0F);
        this.pedRB3 = new ModelRenderer(this, 84, 58);
        this.pedRB3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRB3.addBox(17.0F, 10.0F, -20.0F, 3, 4, 3, 0.0F);
        this.pedRB4 = new ModelRenderer(this, 64, 58);
        this.pedRB4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRB4.addBox(16.0F, 14.0F, -21.0F, 5, 2, 5, 0.0F);
        this.pedRF4 = new ModelRenderer(this, 64, 58);
        this.pedRF4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRF4.addBox(-21.0F, 14.0F, -21.0F, 5, 2, 5, 0.0F);
        this.Candle_drib3 = new ModelRenderer(this, 48, 59);
        this.Candle_drib3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib3.addBox(-17.0F, 4.0F, -19.0F, 1, 2, 1, 0.0F);
        this.pedRB2 = new ModelRenderer(this, 64, 58);
        this.pedRB2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRB2.addBox(16.0F, 8.0F, -21.0F, 5, 2, 5, 0.0F);
        this.wick_LF = new ModelRenderer(this, 64, 69);
        this.wick_LF.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wick_LF.addBox(-31.3F, -2.0F, -31.3F, 1, 2, 1, 0.0F);
        this.wick_LB = new ModelRenderer(this, 64, 69);
        this.wick_LB.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.wick_LB.addBox(-31.3F, -2.0F, 30.3F, 1, 2, 1, 0.0F);
        this.pedLF1 = new ModelRenderer(this, 64, 50);
        this.pedLF1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLF1.addBox(-21.5F, 6.0F, 15.5F, 6, 2, 6, 0.0F);
        this.pedRF3 = new ModelRenderer(this, 84, 58);
        this.pedRF3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRF3.addBox(-20.0F, 10.0F, -20.0F, 3, 4, 3, 0.0F);
        this.pedLB1 = new ModelRenderer(this, 64, 50);
        this.pedLB1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLB1.addBox(15.5F, 6.0F, 15.5F, 6, 2, 6, 0.0F);
        this.Candle_drib7 = new ModelRenderer(this, 48, 59);
        this.Candle_drib7.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib7.addBox(17.0F, 0.0F, 17.0F, 3, 6, 3, 0.0F);
        this.pedRB1 = new ModelRenderer(this, 64, 50);
        this.pedRB1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRB1.addBox(15.5F, 6.0F, -21.5F, 6, 2, 6, 0.0F);
        this.pedLF4 = new ModelRenderer(this, 64, 58);
        this.pedLF4.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLF4.addBox(-21.0F, 14.0F, 16.0F, 5, 2, 5, 0.0F);
        this.Candle_drib6 = new ModelRenderer(this, 48, 59);
        this.Candle_drib6.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib6.addBox(20.0F, 4.0F, 17.9F, 1, 2, 1, 0.0F);
        this.Candle_LB_3 = new ModelRenderer(this, 48, 59);
        this.Candle_LB_3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_LB_3.addBox(-17.0F, 3.0F, 18.0F, 1, 3, 1, 0.0F);
        this.Candle_drib10 = new ModelRenderer(this, 48, 59);
        this.Candle_drib10.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib10.addBox(18.0F, 3.0F, 16.0F, 1, 3, 1, 0.0F);
        this.Candle_drib1 = new ModelRenderer(this, 48, 59);
        this.Candle_drib1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib1.addBox(-19.0F, 2.0F, -21.0F, 1, 4, 1, 0.0F);
        this.Candle_drib2 = new ModelRenderer(this, 48, 59);
        this.Candle_drib2.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_drib2.addBox(-21.0F, 5.0F, -19.0F, 1, 1, 1, 0.0F);
        this.Candle_LB_1 = new ModelRenderer(this, 48, 59);
        this.Candle_LB_1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_LB_1.addBox(-20.0F, 0.0F, 17.0F, 3, 6, 3, 0.0F);
        this.pedLB3 = new ModelRenderer(this, 84, 58);
        this.pedLB3.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedLB3.addBox(17.0F, 10.0F, 17.0F, 3, 4, 3, 0.0F);
        this.pedRF1 = new ModelRenderer(this, 64, 50);
        this.pedRF1.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.pedRF1.addBox(-21.5F, 6.0F, -21.5F, 6, 2, 6, 0.0F);
        this.Base = new ModelRenderer(this, 0, 72);
        this.Base.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Base.addBox(-24.0F, 16.0F, -24.0F, 48, 8, 48, 0.0F);
        this.Candle_LF = new ModelRenderer(this, 48, 59);
        this.Candle_LF.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Candle_LF.addBox(-20.0F, 0.0F, -20.0F, 3, 6, 3, 0.0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        GL11.glPushMatrix();
        GL11.glTranslatef(this.wick_RF.offsetX, this.wick_RF.offsetY, this.wick_RF.offsetZ);
        GL11.glTranslatef(this.wick_RF.rotationPointX * f5, this.wick_RF.rotationPointY * f5, this.wick_RF.rotationPointZ * f5);
        GL11.glScaled(0.6D, 1.0D, 0.6D);
        GL11.glTranslatef(-this.wick_RF.offsetX, -this.wick_RF.offsetY, -this.wick_RF.offsetZ);
        GL11.glTranslatef(-this.wick_RF.rotationPointX * f5, -this.wick_RF.rotationPointY * f5, -this.wick_RF.rotationPointZ * f5);
        this.wick_RF.render(f5);
        GL11.glPopMatrix();
        this.Candle_drib9.render(f5);
        this.Candle_LB_4.render(f5);
        this.Candle_drib5.render(f5);
        this.pedLB4.render(f5);
        this.CirclePad.render(f5);
        this.Candle_LB_2.render(f5);
        this.pedLB2.render(f5);
        this.Candle_drib8.render(f5);
        this.pedLF3.render(f5);
        this.Candle_RF.render(f5);
        this.Candle_drib4.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.wick_RB.offsetX, this.wick_RB.offsetY, this.wick_RB.offsetZ);
        GL11.glTranslatef(this.wick_RB.rotationPointX * f5, this.wick_RB.rotationPointY * f5, this.wick_RB.rotationPointZ * f5);
        GL11.glScaled(0.6D, 1.0D, 0.6D);
        GL11.glTranslatef(-this.wick_RB.offsetX, -this.wick_RB.offsetY, -this.wick_RB.offsetZ);
        GL11.glTranslatef(-this.wick_RB.rotationPointX * f5, -this.wick_RB.rotationPointY * f5, -this.wick_RB.rotationPointZ * f5);
        this.wick_RB.render(f5);
        GL11.glPopMatrix();
        this.Candle_LB.render(f5);
        this.pedRF2.render(f5);
        this.pedLF2.render(f5);
        this.pedRB3.render(f5);
        this.pedRB4.render(f5);
        this.pedRF4.render(f5);
        this.Candle_drib3.render(f5);
        this.pedRB2.render(f5);
        GL11.glPushMatrix();
        GL11.glTranslatef(this.wick_LF.offsetX, this.wick_LF.offsetY, this.wick_LF.offsetZ);
        GL11.glTranslatef(this.wick_LF.rotationPointX * f5, this.wick_LF.rotationPointY * f5, this.wick_LF.rotationPointZ * f5);
        GL11.glScaled(0.6D, 1.0D, 0.6D);
        GL11.glTranslatef(-this.wick_LF.offsetX, -this.wick_LF.offsetY, -this.wick_LF.offsetZ);
        GL11.glTranslatef(-this.wick_LF.rotationPointX * f5, -this.wick_LF.rotationPointY * f5, -this.wick_LF.rotationPointZ * f5);
        this.wick_LF.render(f5);
        GL11.glPopMatrix();
        GL11.glPushMatrix();
        GL11.glTranslatef(this.wick_LB.offsetX, this.wick_LB.offsetY, this.wick_LB.offsetZ);
        GL11.glTranslatef(this.wick_LB.rotationPointX * f5, this.wick_LB.rotationPointY * f5, this.wick_LB.rotationPointZ * f5);
        GL11.glScaled(0.6D, 1.0D, 0.6D);
        GL11.glTranslatef(-this.wick_LB.offsetX, -this.wick_LB.offsetY, -this.wick_LB.offsetZ);
        GL11.glTranslatef(-this.wick_LB.rotationPointX * f5, -this.wick_LB.rotationPointY * f5, -this.wick_LB.rotationPointZ * f5);
        this.wick_LB.render(f5);
        GL11.glPopMatrix();
        this.pedLF1.render(f5);
        this.pedRF3.render(f5);
        this.pedLB1.render(f5);
        this.Candle_drib7.render(f5);
        this.pedRB1.render(f5);
        this.pedLF4.render(f5);
        this.Candle_drib6.render(f5);
        this.Candle_LB_3.render(f5);
        this.Candle_drib10.render(f5);
        this.Candle_drib1.render(f5);
        this.Candle_drib2.render(f5);
        this.Candle_LB_1.render(f5);
        this.pedLB3.render(f5);
        this.pedRF1.render(f5);
        this.Base.render(f5);
        this.Candle_LF.render(f5);
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z)
    {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}
