package com.pahimar.ee3.reference;

public enum GuiId
{
    PORTABLE_CRAFTING,
    CALCINATOR,
    ALUDEL,
    ALCHEMICAL_CHEST,
    ALCHEMICAL_BAG,
    GLASS_BELL,
    RESEARCH_STATION,
    AUGMENTATION_TABLE,
    ALCHEMICAL_TOME,
    TRANSMUTATION_SQUARE
}
